---
- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: restart php5-fpm
  service: name=php5-fpm enabled=yes state=restarted

- name: restart supervisor
  service: name=supervisor enabled=yes state=restarted

- name: restart rabbitmq
  service: name=rabbitmq-server enabled=yes state=restarted

- name: update ca certificates
  command: update-ca-certificates