---
- stat: path=/usr/local/bin/composer
  register: composer
- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  when: composer.stat.exists == false
- file: path=/usr/local/bin/composer state=file mode=0755
- command: composer self-update
  when: composer.stat.exists == true

