---
- stat: path=/home/vagrant/.composer/vendor/bin/drush
  register: drush
- name: Install Drush 8.x
  command: composer global require drush/drush:dev-master
  when: drush.stat.exists == false
  sudo_user: vagrant
- name: Update Drush 8.x
  command: composer global update drush/drush
  when: drush.stat.exists == true
  sudo_user: vagrant
