---
- name: Install MySQL
  apt: pkg=mysql-server-5.6 state=latest

- name: Create wildcard root MySQL user
  mysql_user:
    name: root
    host: "%"
    password: "123"
    priv: "*.*:ALL,GRANT"

- lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    state: present
    regexp: ^bind-address\s*=
    line: bind-address = 0.0.0.0
