---
- name: Add NodeJS 4.x repo
  shell: curl -sL https://deb.nodesource.com/setup_4.x | bash -

- name: Install NodeJS
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs

#@todo The code below doesn't work before Ansible 2, think of a workaround
#- name: Install PhantomJS
#  unarchive:
#    src: https://github.com/bprodoehl/phantomjs/releases/download/v2.0.0-20150528/phantomjs-2.0.0-20150528-u1504-x86_64.zip
#    dest: /opt/phantomjs-2.0.0
#
#- alternatives:
#    name: phantomjs
#    path: /opt/phantomjs-2.0.0/bin/phantomjs
#    link: /usr/local/bin/phantomjs
