---
- name: Install RabbitMQ
  apt: pkg=rabbitmq-server state=latest

- rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_management_visualiser,rabbitmq_tracing,rabbitmq_stomp,rabbitmq_web_stomp,rabbitmq_web_stomp_examples
  notify: restart rabbitmq
