---
- stat: path=/usr/local/bin/wp
  register: wp_cli
- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
  when: wp_cli.stat.exists == false
- file: path=/usr/local/bin/wp state=file mode=0755
- command: wp cli update --allow-root
  when: wp_cli.stat.exists == true
- get_url:
    url: https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash
    dest: /etc/bash_completion.d/wp-cli

